### ISSUE TITLE
--static and mjpg_streamer compatibilty

### ISSUE THREAD

**Issue by KwadFan** [pikvm/ustreamer#128]
Hello,
This is more a Question like a real Issue.
But, for a Project I am working on, I would like to use my own statice files for the inbuild http server.
If I use --static the inbuilt redirect dont work.
My Problem is that I have to keep the redirects that you have implemented to keep mjpg_streamer compatibility.
I tried with some DOM Manipulation in JS but didnt work well. Or has other strange behavior.
Is there a way around this? 

Regards

**Comment by mdevaev** [comment]
I'm sorry, I didn't understand anything. Can you show me a concrete example: what you do, what you get, what you wanted to get.

**Comment by KwadFan** [comment]
As an Example:

-s 127.0.0.1 -p 8080 -m MJPEG --buffers=3 --device-timeout=5 -r 1280x720 -f 30 --static=/home/pi/webcamtest/ustreamer-www/ is used to start ustreamer.

When ustreamer launches I can reach the stream via localhost:8080/stream an see my Page that I created in ustreamer-www, what shows a snapshot from /snapshot and a <div> Container showing the Stream.

But if I type in my Browser http://localhost:8080/?action=stream, I get an 404 and nothing is shown.
How do I do that with the ?action extention I get redirected accordingly to Stream or Snapshot without using my index.html?

**Comment by KwadFan** [comment]
What I try to archieve is that the lower screenshot, shows only the Stream using ?action=stream instead of my --static files.

**Comment by mdevaev** [comment]
Fixed now try from master branch.

**Comment by KwadFan** [comment]
Thank you very much, now it works like a charm :)
I apriciate your work and thank you again for ustreamer :)
