### ISSUE TITLE
Can't make it on raspberry pi zero 

### ISSUE THREAD

**Issue by thomiz** [pikvm/ustreamer#135]
I am pretty sure it worked a year ago, but when I try to install ustreamer on another pi-zero today I only get this trying to make ustreamer:

~~~bash
In file included from ustreamer/http/bev.c:23:
ustreamer/http/bev.h:28:10: fatal error: event2/util.h: Ingen slik fil eller filkatalog
   28 | #include <event2/util.h>
      |          ^~~~~~~~~~~~~~~
~~~

**Comment by mdevaev** [comment]
Apparently, some packages are missing

**Comment by thomiz** [comment]
I did the usual git clone so everything should be there right?

**Comment by mdevaev** [comment]
No. Please follow README guide and install all necessary packages.

**Comment by thomiz** [comment]
Will do, probably OMX og GPIO missing then.

**Comment by mdevaev** [comment]
libevent also

**Comment by thomiz** [comment]
Got it, after installing all the dependencies the make goes OK. Sorry.
