### ISSUE TITLE
fails to compile on Raspbian Bullseye 64 bit - missing something

### ISSUE THREAD

**Issue by mytechguyri** [pikvm/ustreamer#144]
/usr/bin/ld: skipping incompatible /opt/vc/lib/libvcsm.so when searching for -lvcsm
/usr/bin/ld: cannot find -lvcsm
/usr/bin/ld: skipping incompatible /opt/vc/lib/libvcsm.so when searching for -lvcsm
/usr/bin/ld: skipping incompatible /opt/vc/lib/libopenmaxil.so when searching for -lopenmaxil
/usr/bin/ld: cannot find -lopenmaxil
/usr/bin/ld: skipping incompatible /opt/vc/lib/libopenmaxil.so when searching for -lopenmaxil
/usr/bin/ld: skipping incompatible /opt/vc/lib/libmmal.so when searching for -lmmal
/usr/bin/ld: cannot find -lmmal
/usr/bin/ld: skipping incompatible /opt/vc/lib/libmmal.so when searching for -lmmal
/usr/bin/ld: skipping incompatible /opt/vc/lib/libmmal_core.so when searching for -lmmal_core
/usr/bin/ld: cannot find -lmmal_core
/usr/bin/ld: skipping incompatible /opt/vc/lib/libmmal_core.so when searching for -lmmal_core
/usr/bin/ld: skipping incompatible /opt/vc/lib/libmmal_util.so when searching for -lmmal_util
/usr/bin/ld: cannot find -lmmal_util
/usr/bin/ld: skipping incompatible /opt/vc/lib/libmmal_util.so when searching for -lmmal_util
/usr/bin/ld: skipping incompatible /opt/vc/lib/libmmal_vc_client.so when searching for -lmmal_vc_client
/usr/bin/ld: cannot find -lmmal_vc_client
/usr/bin/ld: skipping incompatible /opt/vc/lib/libmmal_vc_client.so when searching for -lmmal_vc_client
/usr/bin/ld: skipping incompatible /opt/vc/lib/libmmal_components.so when searching for -lmmal_components
/usr/bin/ld: cannot find -lmmal_components
/usr/bin/ld: skipping incompatible /opt/vc/lib/libmmal_components.so when searching for -lmmal_components
collect2: error: ld returned 1 exit status

**Comment by mdevaev** [comment]
[Bullseye threw out some libraries and broke compatibility](https://github.com/pikvm/ustreamer/issues/123). I'm working on a 5.0 release that will fix this problem. For now, I recommend that you don't use the WITH_OMX flag.
