### ISSUE TITLE
FEAT: Ability to exec command when client joins

### ISSUE THREAD

**Issue by aurimasniekis** [pikvm/ustreamer#147]
At the moment because ustreamer doesn't support multiple different formats from v4l2 supported, I am running akvcam with FFmpeg to convert to a suitable one and everything is fine, but it means that FFmpeg is running nonstop even if there are no clients.

It would be nice if there was a possibility to have some exec functions on when there are clients aka the first client joined and then all clients left, so I could boot/kill the FFmpeg without wasting resources in the background.

**Comment by mdevaev** [comment]
Do you put ffmpeg after ustreamer? I'm not sure that I quite understant the chain.

**Comment by mdevaev** [comment]
Sup?

**Comment by mdevaev** [comment]
No answer, so I'm closing it. Let me know if you're still interested.
