### ISSUE TITLE
Raspberry Pi 4 stream issue with 2 webcams

### ISSUE THREAD

**Issue by ethanbowering24** [pikvm/ustreamer#156]
After starting a stream with 
`./ustreamer --device /dev/video0 -r 1280x720 -f 30 -m MJPEG -c HW -s 192.168.40.127 -p 8080 --drop-same-frames=30`
and in another terminal (using tmux)
`./ustreamer --device /dev/video2 -r 1280x720 -f 30 -m MJPEG -c HW -s 192.168.40.127 -p 8081 --drop-same-frames=30`

These are Lenovo webcams, and the output of `v4l2-ctl -d /dev/video0 --all' shows that these cameras output MJPG frames.

For short time, both streams have perfect video. However after a short amount of time (~ 1 min) whichever camera I started second starts to stutter, then freeze and eventually shows no signal, sometimes reconnects and is fine for some time but it always happens again.  When I use --log-level 3, you can see the log prints stutter as the stream stutters

One thing to note is that I get an error "Device doesn't support setting of HW encoding quality paramaters". I am not sure what is causing this error. I have tried tons of things (lowering resolution and FPS seems to delay when the issues start to occur) including plugging the cameras into a powered hub which I read somewhere might help.

Any advice is greatly appreciated.

**Comment by mdevaev** [comment]
Hello.

> For short time, both streams have perfect video. However after a short amount of time (~ 1 min) whichever camera I started second starts to stutter, then freeze and eventually shows no signal, sometimes reconnects and is fine for some time but it always happens again.

This is the hardware problem. The cameras lack the bandwidth of the single USB controller.

> Device doesn't support setting of HW encoding quality paramaters

It's not really an error. It's just that the cameras don't allow you to adjust the image quality.
