### ISSUE TITLE
Extra packages needed to build `WITH_JANUS=1`

### ISSUE THREAD

**Issue by reedy** [pikvm/ustreamer#161]
Noticed on debian I needed to install: `libasound2-dev libspeexdsp-dev libopus-dev`

Similar to https://github.com/pikvm/ustreamer/blob/master/README.md#building we probably want something mentioning in https://github.com/pikvm/ustreamer/blob/master/docs/h264.md#installation

**Comment by mdevaev** [comment]
Fixed now
