### ISSUE TITLE
Stream not available in QuickTime Player and VLC?

### ISSUE THREAD

**Issue by marcelstoer** [pikvm/ustreamer#185]
`my-pi:8080/stream` works fine in Safari, Chrome and Firefox - individually and in parallel. Yet, the same URL fails to open in both QuickTime Player (File -> Open Location) and VLC (File -> Open Network).

Since it doesn't work in _either_ of the two applications I am suspecting an issue with uStreamer.

Can anyone confirm my findings?

**Comment by marcelstoer** [comment]
It is much more banal, sorry. As so often, the problem was in front of the computer 😄 . `my-pi:8080/stream` fails but `http://my-pi:8080/stream` works fine with VLC. No progress with QuickTime yet but I'm confident now that it's not a uStreamer issue. Sorry for the noise.

**Comment by mdevaev** [comment]
No problem)
