### ISSUE TITLE
Confused about H.264 video, docs issue?

### ISSUE THREAD

**Issue by marcelstoer** [pikvm/ustreamer#191]
I am a little confused about [docs/h264.md](https://github.com/pikvm/ustreamer/tree/master/docs/h264.md) and µStreamer's H.264 capabilities in general.

Initially I thought µStreamer could produce a H.264 stream for browsers (that have H.264-capabilities) to consume directly. I felt I was on the right track when docs intro says

> This guide explains how to configure µStreamer to provide an H.264 video stream

Yet, it appears that there is no H.264 without setting up Janus for WebRTC as well. Is that correct? Maybe I need to brush up my limited knowledge in that area on the correlation between H.264 and WebRTC...

**Comment by mdevaev** [comment]
It is impossible to stream H.264 without WebRTC, so right now Janus usage is mandatory for this.
