### ISSUE TITLE
ustreamer heading towards fedora

### ISSUE THREAD

**Issue by tao-j** [pikvm/ustreamer#193]
The package review is passed, should be available in next week.

https://bugzilla.redhat.com/show_bug.cgi?id=2140323

It is suggested by the Fedora project that we notify the upstream.

Thanks for the contributon.

**Comment by mdevaev** [comment]
Thank you!

**Comment by mdevaev** [comment]
I've added link to the package to README file.

**Comment by tao-j** [comment]
Thanks. You may also consider Debian/Ubuntu packages here:

https://packages.ubuntu.com/jammy/ustreamer

https://packages.debian.org/sid/ustreamer
