### ISSUE TITLE
Is there a possibility to offer a web page can set camera parameters?

### ISSUE THREAD

**Issue by xmmwc** [pikvm/ustreamer#20]
My camera is set manually, it's too troublesome to set up with the command line. And I am not very good at it. Could you provide a webpage to set these camera parameters?
ps: thank you very much for this great job

**Comment by mdevaev** [comment]
Hi. Unfortunately, this is not possible now. Ustreamer was made primarily for the needs of pikvm, so initially it was not provided for regulating broadcast parameters without restarting. I plan to implement this feature, but this task is not a priority in the near future.

**Comment by xmmwc** [comment]
Thanks for your reply, I will temporarily looking for alternatives. :-)
