### ISSUE TITLE
[Feature request] Region of Interest (ROI) option

### ISSUE THREAD

**Issue by DoktorJ** [pikvm/ustreamer#200]
My use case for uStreamer is admittedly perhaps niche, but basically I want a sort of digital zoom so that only an area of my camera gets streamed. Basically there's only a small area in the camera's field of view that we actually care about, and I'd just as soon crop out the rest to make it easier to focus on the... Region Of Interest. The old `raspivid` command had a `--roi` argument that:

> Allows part of the camera sensor to be specified as the capture source, rather than the entire sensor—effectively cropping the captured image. This option takes floating-point normalised XY coordinates between 0.0 and 1.0. To use the quarter of the sensor at the upper left, for example, the values 0,0,0.25,0.25 should be used.

Might there be a (hopefully relatively trivial) way to implement this in ustreamer?  Alternatively, a hack/workaround to accomplish the same thing?

**Comment by mdevaev** [comment]
Hello. Ustreamer does not have any ability to process video, it is a conscious decision for performance. If the traffic does not matter, I recommend doing post-processing in the browser using CSS or something like that.
