### ISSUE TITLE
[REQUEST] Camera Module 3 Support

### ISSUE THREAD

**Issue by addohm** [pikvm/ustreamer#212]
I just learned that [picam module 3](url=https://www.raspberrypi.com/products/camera-module-3/) is not supported....the hard way.

In the meanwhile, could you put in the wiki or readme that it's not supported to save other's time?

Thanks!

**Comment by boehser-enkel** [comment]
Yes please

**Comment by mdevaev** [comment]
Hi. I've got a camera and experimented with it. Too much work will be needed for native support, but Raspberry offers "libcamerify", which works fine with uStreamer. On Raspberry OS, install `libcamera-tools` and run as follows: `libcamerify ./ustreamer -r 1920x1080 --encoder=m2m-image`.
