### ISSUE TITLE
Low FPS when accesing server from outside LAN

### ISSUE THREAD

**Issue by Andrei-Iosifescu123** [pikvm/ustreamer#218]
I am running uStreamer on a Raspberry Pi 2B+. It works great when I am accesing it from LAN, but whenever I connect to it using VPN/port forwarding, I always get low (6-7) FPS compared to 25 locally. This is my command: `./ustreamer -r 1280x720 -m MJPEG -f 25 -s 0.0.0.0 -c M2M-IMAGE`.
Any help would be appreciated.

**Comment by mdevaev** [comment]
Hello. The reason is the low bandwidth of the channel. MJPEG is a heavy format.

**Comment by Andrei-Iosifescu123** [comment]
> Hello. The reason is the low bandwidth of the channel. MJPEG is a heavy format.

I have 100 Mbps connection on both sides, so this could not be the problem.

**Comment by mdevaev** [comment]
You should check how big the delays are and whether the performance when transferring data from one end to the other is really fast. There really is nothing here that can be configured from the software side.

**Comment by Andrei-Iosifescu123** [comment]
> You should check how big the delays are and whether the performance when transferring data from one end to the other is really fast. There really is nothing here that can be configured from the software side.

The average ping is about 35ms, and the speed is around 80Mbps. I think it aslo has something to do with `queued_fps`, since it is 24, and actual fps is 1. So while all frames are being encoded (`"captured_fps": 25`), not all reach the end device. 
![Screenshot_20230603_152058_com android chrome](https://github.com/pikvm/ustreamer/assets/35394195/2a5c0fff-09a8-41be-b51d-8ce783431ec9)

**Comment by mdevaev** [comment]
Which browser do you use?

**Comment by Andrei-Iosifescu123** [comment]
> Which browser do you use?

For viewing the stream, I use an app called [IP Camera](https://play.google.com/store/apps/details?id=com.shenyaocn.android.WebCam)

**Comment by mdevaev** [comment]
Please try the desktop browser like Chrome.

**Comment by Andrei-Iosifescu123** [comment]
> Hello. The reason is the low bandwidth of the channel. MJPEG is a heavy format.

Is there any way to stream H264 instead of MJPG? It should have a much lower bandwidth.

**Comment by mdevaev** [comment]
Yes, but not over HTTP.

**Comment by Andrei-Iosifescu123** [comment]
> Yes, but not over HTTP.

Over RTSP? How can I do that? I didn't see any options regarding rtsp streaming.

**Comment by mdevaev** [comment]
https://github.com/pikvm/ustreamer/blob/master/docs/h264.md

**Comment by Andrei-Iosifescu123** [comment]
> https://github.com/pikvm/ustreamer/blob/master/docs/h264.md

I tried this, but when I ran `./ustreamer -r 1280x720 -f 25 --h264-sink demo::ustreamer::h264 --h264-sink-rm -s 0.0.0.0` I got an error:
```
-- ERROR [61288.860    stream] -- H264: Can't set option V4L2_CID_MPEG_VIDEO_H264_MIN_QP: Invalid argument
-- ERROR [61288.860    stream] -- H264: Encoder destroyed due an error (prepare)
```

**Comment by mdevaev** [comment]
Is it raspberry pi?

**Comment by Andrei-Iosifescu123** [comment]
> Is it raspberry pi?

Yes, Raspberry Pi 2B+ running Ubuntu 20.04

**Comment by mdevaev** [comment]
Probably Ubuntu doesn't have all needed kernel patches to support it. Try the latest Raspberry OS.

**Comment by Andrei-Iosifescu123** [comment]
> Probably Ubuntu doesn't have all needed kernel patches to support it. Try the latest Raspberry OS.

But since it's a USB camera it should work on any kind of computer running Ubuntu - not only Raspberry Pis.

**Comment by mdevaev** [comment]
No because this is not related with camera, but with hardware h264 encoder.

Also you need to use yuyv or uyvy for the input format, not mjpeg/jpeg, otherwise the image from camera will be decoded on cpu befure h264 encoding.

**Comment by Andrei-Iosifescu123** [comment]
> No because this is not related with camera, but with hardware h264 encoder.
> 
> Also you need to use yuyv or uyvy for the input format, not mjpeg/jpeg, otherwise the image from camera will be decoded on cpu befure h264 encoding.

The problem is that my camera can only do 10FPS using yuyv image format and 25 using MJPG. Is it possible to encode the MJPG from the camera to a H264 stream using hardware acceleration?

**Comment by mdevaev** [comment]
Yes but it will slow.

**Comment by Andrei-Iosifescu123** [comment]
> Yes but it will slow.

So there's no way to get 25 FPS out of this camera using uStreamer and Janus?

**Comment by mdevaev** [comment]
No, only for specific capture devices or cameras. For example, it should work for Camera Module 3 (because of CSI bus), but I didn't test it. Also it will work with HDMI capture. But USB not for USB camera I think.

**Comment by Andrei-Iosifescu123** [comment]
> No, only for specific capture devices or cameras. For example, it should work for Camera Module 3 (because of CSI bus), but I didn't test it. Also it will work with HDMI capture. But USB not for USB camera I think.

I think i'll just stick with ffmpeg for now. Thanks for your help.

**Comment by mdevaev** [comment]
You're welcome. I'm sorry it didn't suit you.
