### ISSUE TITLE
Cannot set correct resolution

### ISSUE THREAD

**Issue by OliverGruenberg** [pikvm/ustreamer#221]
Hi there,

I have a 48MP USB camera for testing...

Of course I can query it via:
v4l2-ctl -d /dev/video0 --list-formats-ext

Result is:
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture

	[0]: 'MJPG' (Motion-JPEG, compressed)
		Size: Discrete 3840x2160
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 1920x1080
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 1280x720
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 4000x3000
			Interval: Discrete 0.067s (15.000 fps)
		Size: Discrete 8000x6000
			Interval: Discrete 0.200s (5.000 fps)
	[1]: 'YUYV' (YUYV 4:2:2)
		Size: Discrete 1920x1080
			Interval: Discrete 0.200s (5.000 fps)
			Interval: Discrete 0.100s (10.000 fps)
		Size: Discrete 800x600
			Interval: Discrete 0.040s (25.000 fps)
		Size: Discrete 1920x1080
			Interval: Discrete 0.200s (5.000 fps)
			Interval: Discrete 0.100s (10.000 fps)
		Size: Discrete 640x480
			Interval: Discrete 0.050s (20.000 fps)

Question:
I want to capture an image at full resolution, in my case 48MP.
How can I do this?

Running the command

$ ustreamer --host=0.0.0.0 --port=8080 --resolution 8000x6000  

results in 

Invalid height of '--resolution=8000x6000': min=120, max=4320

Any idea?

**Comment by mdevaev** [comment]
Hello. We just have a limit. I've increased it, please take a new version 5.41 from master branch.
