### ISSUE TITLE
upgrade to libgpio-2.0

### ISSUE THREAD

**Issue by tao-j** [pikvm/ustreamer#225]
arch still has the 1.6 https://aur.archlinux.org/packages/libgpiod-git

fedora is moving to 2.0 https://src.fedoraproject.org/rpms/libgpiod

2.0 breaks some api and according to my initial research

**Comment by mdevaev** [comment]
I'll do it when Arch gets libgpiod2.

**Comment by mdevaev** [comment]
Added in master branch.

**Comment by jerry-yuan** [comment]
@mdevaev Have you fixed this? I was failed for the reason that arch provided libgpiod with v2 when building ustreamer with `makepkg -si` at `pkg/arch`:
![image](https://github.com/pikvm/ustreamer/assets/13380647/6656a7cf-3f36-44ed-9736-080a91779e9f)
And I have confirmed that ustreamer still using libgpiod v1 apis and my libgpiod has been upgraded into v2:
![image](https://github.com/pikvm/ustreamer/assets/13380647/8559680a-e42c-4e15-88aa-81ebb8c151c4)

**Comment by jerry-yuan** [comment]
> @mdevaev Have you fixed this? I was failed for the reason that arch provided libgpiod with v2 when building ustreamer with `makepkg -si` at `pkg/arch`: ![image](https://private-user-images.githubusercontent.com/13380647/333809401-6656a7cf-3f36-44ed-9736-080a91779e9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NTAzMTYsIm5iZiI6MTcxNjY1MDAxNiwicGF0aCI6Ii8xMzM4MDY0Ny8zMzM4MDk0MDEtNjY1NmE3Y2YtM2YzNi00NGVkLTk3MzYtMDgwYTkxNzc5ZTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDE1MTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ODBkMGMwNjlkMTg2OTRiNWVjOTBhZTkwNTM1MDMzZWEyODFjMzRhMDQ1N2I3NzUzMThhYTg1NzExZTlhMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yCoSMkFvVGEnIiONWP7QVesjOlnk7GjxVxGzPht-PF4) And I have confirmed that ustreamer still using libgpiod v1 apis and my libgpiod has been upgraded into v2: ![image](https://private-user-images.githubusercontent.com/13380647/333809479-8559680a-e42c-4e15-88aa-81ebb8c151c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NTAzMTYsIm5iZiI6MTcxNjY1MDAxNiwicGF0aCI6Ii8xMzM4MDY0Ny8zMzM4MDk0NzktODU1OTY4MGEtZTQyYy00ZTE1LTg4YWEtODFlYmI4YzE1MWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDE1MTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2NTRmZDIzYjg1Yzk3NmJiMWMyODJjMzk0ZmUzMTQ3NjE2Mjc4ZmUyMWFiMDk4MGZiNTAyOWYwOGRkZDAxYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zTUDnMgJ1nzHWEO1bvj0UL-CCCUC1eYvK1Fpg48YarM)

I have solved this, I checked the commits and I found you added a macro `HAVE_GPIOD2` in this [commit](https://github.com/pikvm/ustreamer/commit/d9b5f2b03d079396548f71af3c2036b8433c6961) by execute `pkg-config` to check if the libgpiod v2 is exist. But in my case the `pkg-config` is not installed, which will make this always fails and down-grade to use libgpiod v1 apis(I was build this in a clear docker container). Maybe you should add a check of pkg-config's existance?

**Comment by mdevaev** [comment]
It makes sense. Added.
