### ISSUE TITLE
Wait for first frame when snapshot is requested on startup

### ISSUE THREAD

**Issue by pipe01** [pikvm/ustreamer#228]
When using the `--systemd` option along with SystemD `.service` and `.socket` files that start ustreamer when a TCP connection is received, if ustreamer is started by requesting a `/snapshot` the "NO SIGNAL" image is received, instead of a camera frame.
It would be great if instead it waited until the first frame is received and then sent that, maybe a timeout parameter could be added to limit how long it will wait for the image.

**Comment by mdevaev** [comment]
Hello. I'll try to fix it somehow when I have time.

**Comment by mdevaev** [comment]
Sup. It will be fixed in the next release.
