### ISSUE TITLE
Unable to capture Raspberry PI V2 camera streaming

### ISSUE THREAD

**Issue by sreedharch** [pikvm/ustreamer#240]
I tried connecting "Raspberry PI 5MP Camera Board Module" V2 camera to pikvm and started running the command:
$ sudo modprobe bcm2835-v4l2
$ libcamerify ./ustreamer --host :: -e m2m-image

I notice that the ustreamer throws following error:
Device fd=8 opened
Can't query device capabilities: Inappropriate ioctl for device
Device fd=8 closed

pikvm is unable to capture the camera streaming. Can you please help on this.

**Comment by sreedharch** [comment]
Enabled the "legacy camera" mode in "raspi-config" util

**Comment by mdevaev** [comment]
Try to increase resolution

**Comment by mdevaev** [comment]
Okay, I've added info about raspi-config, thank you.
