### ISSUE TITLE
H264: Can't open encoder device: No such file or directory

### ISSUE THREAD

**Issue by Eric-168** [pikvm/ustreamer#244]
./ustreamer -d /dev/video0 --h264-sink kvmd::ustreamer::h264 --h264-sink-mode 777 --h264-sink-rm --encoder CPU
-- INFO  [899.406      main] -- Starting PiKVM uStreamer 5.45 ...
-- INFO  [899.406      main] -- Using internal blank placeholder
-- INFO  [899.406      main] -- Using H264-sink: kvmd::ustreamer::h264
-- INFO  [899.407      main] -- Listening HTTP on [127.0.0.1]:8080
-- INFO  [899.407    stream] -- Using V4L2 device: /dev/video0
-- INFO  [899.408    stream] -- Using desired FPS: 0
-- INFO  [899.408      http] -- Starting HTTP eventloop ...
-- INFO  [899.408    stream] -- H264: Initializing encoder ...
-- INFO  [899.414    stream] -- H264: Configuring encoder: DMA=0 ...
-- ERROR [899.414    stream] -- H264: Can't open encoder device: No such file or directory
-- ERROR [899.414    stream] -- H264: Encoder destroyed due an error (prepare)

**Comment by mdevaev** [comment]
It's working only on Raspberry with hardware encoder

Пт, 17 нояб. 2023 г. в 11:29, Eric-168 ***@***.***>:

**Comment by Eric-168** [comment]
Thank you very much, orange pi has a lower cost, I hope it can be adapted

**Comment by mdevaev** [comment]
I have already told you that I officially support only Raspberry. There are hundreds of boards on ARM, each with its own surprises, and I have no desire to deal with them. I only accept patches for them, and only if they don't interfere with Raspberry support.
