### ISSUE TITLE
Raspberry Pi 5 with Camera Module V3

### ISSUE THREAD

**Issue by Samueleitor6** [pikvm/ustreamer#248]
Hi there! I've been using streamer with Raspberry Pi 4 with raspbian Bulleye, but when y switched to Raspberry Pi 5 with Raspbian Bookworm I've been trying to start stream but I can't. This is the log:

-- INFO  [55007.890    stream] -- Device fd=8 opened
-- INFO  [55007.890    stream] -- Using capture type: single-planar
-- INFO  [55007.890    stream] -- Using input channel: 0
-- INFO  [55007.890    stream] -- Using resolution: 1920x1080
-- INFO  [55007.890    stream] -- Using format: YUYV
-- INFO  [55007.890    stream] -- Querying HW FPS changing is not supported
-- INFO  [55007.890    stream] -- Using IO method: MMAP
-- INFO  [55007.893    stream] -- Requested 2 device buffers, got 3
-- ERROR [55007.893    stream] -- Can't start capturing: Invalid argument
-- INFO  [55007.894    stream] -- Device fd=8 closed
-- INFO  [55007.894    stream] -- Sleeping 1 seconds before new stream init ...

If somebody knows a way to make it work with this hardware and software that tells me here.

Thank you very much in advance!

**Comment by Crocodile94** [comment]
Same hardware with HQ camera and i got this error too.

**Comment by mdevaev** [comment]
Hello. Please install `libcamera-tools` and `libcamera-v4l2` and try `libcamerify ustreamer ...`.

**Comment by Samueleitor6** [comment]
Thank you so much!! That solve my issue, it works perfectly now!

**Comment by mdevaev** [comment]
:ok_hand:
