### ISSUE TITLE
ustreamer crash on FreeBSD 14 and 15 on amd64 arch

### ISSUE THREAD

**Issue by rosorio** [pikvm/ustreamer#259]
After upgrading from FreeBSD 13 to 14 and 15, ustreamer start to crash at startup.

The exact command I run was "ustreamer -d /dev/video0 -s 192.168.1.58 -p 8080"

I didn't investigate too much about this issue but I use ktrace output who list the syscalls done by the application before crash.
[dump.txt](https://github.com/pikvm/ustreamer/files/14284377/dump.txt)

**Comment by mdevaev** [comment]
Maybe it should be recompiled?

I'm not too much of an expert in FreeBSD.

**Comment by mdevaev** [comment]
> Maybe it should be recompiled?

Could you check it?

**Comment by mdevaev** [comment]
Sup?

**Comment by mdevaev** [comment]
No feedback, closing.
