### ISSUE TITLE
Can't update manually: ustreamer new version available

### ISSUE THREAD

**Issue by wwian** [pikvm/ustreamer#265]
I saw in my crowsnest.log that there is a new version of ustreamer:
`[03/06/24 11:35:39] crowsnest: Version Control: ustreamer new version available: 8f0acb2 (v5.57).`

Following the update procedure, the system tells me that I'm already up to date:
```
thor@mainsail:~/crowsnest/bin $ cd ustreamer
thor@mainsail:~/crowsnest/bin/ustreamer $ git pull
Already up to date.
```

What am I missing? Thank you for any assistance you can provide!

**Comment by mdevaev** [comment]
Hello. What does the `git log` show on the top?

**Comment by mdevaev** [comment]
Well, probably your system pulled it already.

**Comment by mdevaev** [comment]
Solved I guess.
