### ISSUE TITLE
http input ?

### ISSUE THREAD

**Issue by bellad17** [pikvm/ustreamer#267]
hi , it's possible input http://IP:8080 instead of  device ?
because my camera ( esp32-cam ) is http://192.168.1.230:8080 that I want stream out http://192.168.1.51:8080 
on debian buster
thank

**Comment by mdevaev** [comment]
Hello. No, it's not possible. You can use https://github.com/jacksonliam/mjpg-streamer for this.

**Comment by bellad17** [comment]
ok thank you , i try
