### ISSUE TITLE
Use VGA Acquisition card will Image dislocation

### ISSUE THREAD

**Issue by sksorth** [pikvm/ustreamer#280]
My parameter configuration is：ustreamer --device=/dev/video9 --host=0.0.0.0 --port=8010 --allow-origin=\* -r 1920x1080 -f 60 -m MJPEG -c M2M-VIDEO --debug &

such as：

![234](https://github.com/pikvm/ustreamer/assets/144311554/54ddab2d-a91e-4109-83e6-44cf94de7aa0)
![123](https://github.com/pikvm/ustreamer/assets/144311554/8f2ea565-ae6e-4cff-9149-3e65a76ba80e)

**Comment by mdevaev** [comment]
Probably this is a driver problem.

**Comment by sksorth** [comment]
But it will not appear on the HTMI collection card,If you use the frame rate of 30fps on VGA, it will occasionally appear several times, for example: 3 minutes 5 times.

**Comment by sksorth** [comment]
And I use FFMPEG to collect, there will be no such situation.

**Comment by mdevaev** [comment]
Try to remove option `-c M2M-VIDEO`

**Comment by sksorth** [comment]
I changed a development board to solve, it may indeed be a driver's problem.
