### ISSUE TITLE
Streams - Disk and Network

### ISSUE THREAD

**Issue by cloudchef-wyatt** [pikvm/ustreamer#291]
Is there a way to save a high resolution camera feed to disk, while also maintaining the ability to stream to devices on the network?

A flow like this:

> connected_clients = [<client 1>]
>
> feed = camera.read() # a raw camera stream
> save(feed.encode("high resolution"), "myfile.mp4")
> stream(feed.encode("low resolution"), connected_clients)

Thanks!

**Comment by mdevaev** [comment]
Hello. You can use shared memory sinks and python library for this. See ustreamer's manpage and code example: https://github.com/pikvm/kvmd/blob/master/kvmd/clients/streamer.py#L176
