### ISSUE TITLE
Stream the CSI input through ustreamer to the HDMI out of the RPi ?

### ISSUE THREAD

**Issue by reukiodo** [pikvm/ustreamer#292]
Is this just a simple command or an option for the [service](https://github.com/pikvm/ustreamer/issues/16)?

Or perhaps is this a separate client service that needs to depend on the ustreamer daemon service?

**Comment by mdevaev** [comment]
Hello. You can try some workarounds described here: https://github.com/pikvm/pikvm/issues/157

Please note the last DRM method is not available on commin Raspberry board and working only on PiKVM hardware.
