### ISSUE TITLE
Ustreamer causing WLAN1 network interface to go DOWN after connection from remote device

### ISSUE THREAD

**Issue by zimmertr** [pikvm/ustreamer#293]
I have a Raspberry Pi that I use to run my 3D Printer. This Raspberry Pi runs a piece of software called [Crowsnest](https://github.com/mainsail-crew/crowsnest) which uses ustreamer to stand up a webcam server so that people can monitor their 3D prints while they're occuring. This Raspberry Pi is installed inside my 3D printer's electronics compartment which causes the wireless reception to be poor. To solve this, I've installed a USB Wireless Adapter with an antenna outside of the chassis. 

All of this works great. However, the moment I try and load the webcam feed, ustreamer appears to set the `wlan1` network interface to `DOWN` which breaks the network connectivity to the device. I can see through a monitor connected to the Raspberry Pi that it continues to function. And I can still interact with it just fine. But it loses network connectivity.

At first I thought this was an issue with Crowsnest. But after [filing an issue](https://github.com/mainsail-crew/crowsnest/issues/276) with that project and talking with a dev, it appears to actually be an issue with ustreamer. Here is a video recording that triggers the bug to occur: https://youtu.be/LSgYNcJOXDE

There are a few other videos I recorded that are linked in that thread. Namely, one that executes iperf and demonstrates that the device is not failing when the bandwidth load is high. https://www.youtube.com/watch?v=lghwhJxn3MU

I forgot to show in the video above, but I'm currently running version 6.16 of ustreamer as well.

**Comment by mdevaev** [comment]
Hello. It's a very weird problem. Ustreamer did nothing with network interfaces so I'm inclined to think that this is a problem with the kernel. There is simply nothing to fix on the part of ustreamer, because it uses normal socket operations.

I know this is not the answer you expected, but I really don't know how I can help. Sorry.

**Comment by zimmertr** [comment]
I noticed that `dmesg` was continuously dumping the following error message:

> brcmfmac: brcmf_set_channel: set chanspec fail, reason -52

<img width="1013" alt="Screenshot 2024-10-25 at 11 14 55 AM" src="https://github.com/user-attachments/assets/2ffb43ac-d51e-4c19-846b-04487921c822">

This is interesting, because `brcmfmac` is the driver used by the Raspberry Pi's internal `wlan0` NIC

<img width="315" alt="Screenshot 2024-10-25 at 11 15 31 AM" src="https://github.com/user-attachments/assets/106376c6-e7a0-40f8-9678-e01073994b9b">

I set up a second NetworkManager connection profile for `wlan0` and enabled it and rebooted.  Then those errors stopped getting logged.

<img width="759" alt="Screenshot 2024-10-25 at 11 17 12 AM" src="https://github.com/user-attachments/assets/8ffca7fd-861b-4d53-96fb-cc02e122185d">

Afterwards, I went ahead and started up a ustreamer server again and connected to it over 192.168.30.170 via `wlan1` as usual and it did not crash!

However, using `bmon`, I can see that `wlan0` is the one transferring data continuously, NOT `wlan1`. Despite the fact that I am hitting the `ustreamer` server over `wlan1`'s IP Address.

<img width="1012" alt="Screenshot 2024-10-25 at 11 18 33 AM" src="https://github.com/user-attachments/assets/5c1229f1-d696-4b76-b09f-8c6d0f8525ae">

Like, I'm happy things are working right now. But something is still wrong. `ustreamer` is only seemingly functional when it can use `wlan0`. And even when I connect to the Raspberry Pi over `wlan1`, I still see that `wlan0` is being used to transfer data. This is problematic because the wireless reception of that NIC is poor, and I can only get 7-11FPS over the 720p stream. Which is what originally led to me purchasing the USB wireless adapter to begin with.

<img width="498" alt="Screenshot 2024-10-25 at 11 20 26 AM" src="https://github.com/user-attachments/assets/a0c98d35-2502-49a3-980a-6700bfc5f3e1">

**Comment by zimmertr** [comment]
Seems to have been a `mt7921u` driver issue. Solution: [here](https://github.com/mainsail-crew/crowsnest/issues/276#issuecomment-2439076152).

**Comment by mdevaev** [comment]
Glad to hear it.
