### ISSUE TITLE
rtsp source

### ISSUE THREAD

**Issue by thewh1teagle** [pikvm/ustreamer#299]
Hi,
Does it possible to get the input from rtsp?
I want to connect to rtsp camera and stream it as mjpeg to webview based desktop app so I can see rtsp in the webview.

**Comment by mdevaev** [comment]
Hello. No, ustreamer is only for v4l2 devices.

**Comment by RSATom** [comment]
@thewh1teagle did you find any solution? I have some tool but it can be too complicated for your case...
