### ISSUE TITLE
Official Docker images

### ISSUE THREAD

**Issue by PascalHonegger** [pikvm/ustreamer#32]
Given the popularity of docker it would be really nice if you're able to simply run ustreamer with a one-line docker command without installing anything. Here are a few points which would have to be done in order to achieve said goal:

- [x] Create Dockerfile / .dockerignore
- [x] Ensure Dockerfile supports multiple architectures (amd64, armv7, ...)
- [x] Automatically build and tag new versions, [for example using GitHub Actions and buildx](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/ )
- [x] Add tagged build with Raspberry Pi OMX / GPIO support
- [x] Update documentation

**Comment by mdevaev** [comment]
The latest versions of ustreamer use libgpiod, which is available on all platforms include x86_64.

**Comment by badsmoke** [comment]
in the meantime i have already built a docker container for myself, for all who are interested

"https://hub.docker.com/repository/docker/badsmoke/ustreamer"

arch = amd64

**Comment by tomaszduda23** [comment]
@mdevaev do you have any plan to make docker image public on dockerhub?

**Comment by mdevaev** [comment]
What do I need to do for this?

**Comment by tomaszduda23** [comment]
It seems that image is uploaded when you create new tag but repository is private on dockerhub. You can change it in repository settings 'make public'. Do you use pikvm/ustreamer in dockerhub?

**Comment by mdevaev** [comment]
Hm, it was pushed to https://hub.docker.com/repository/docker/mdevaev/ustreamer

**Comment by tomaszduda23** [comment]
https://github.com/pikvm/ustreamer/commit/1ff021d9aca93fa9eb4175e600909cf1a8315ea5 this could be changed here. Do you own pikvm name? I'm not able to check who is the owner of that.

**Comment by mdevaev** [comment]
Yes, I don't know why it's not working :/

**Comment by tomaszduda23** [comment]
secrets.DOCKERHUB_USERNAME <- the name is taken from this so you can change it or merge https://github.com/pikvm/ustreamer/pull/189. I'm not able to test it myself though.

**Comment by mdevaev** [comment]
https://hub.docker.com/r/pikvm/ustreamer/tags
