### ISSUE TITLE
Can't resume stream after unplugging HDMI

### ISSUE THREAD

**Issue by depauwjimmy** [pikvm/ustreamer#38]
Hello,

I am on Rasp4 with the B101 card to stream an HDMI video flux (either a camera or laptops)
It can be plugged-in and out on a regular basis (with a large amount of different devices) but i never want the stream to shutdown which ustreamer should help me with.

Now i have installed the last raspbian version as of this message and compiled ustreamer.

My run command is

`./ustreamer --host=192.168.1.166  --port=15666 --format=uyvy --encoder=omx --workers=3`

It works fine and i have my video stream, unplugging properly shows NOSIGNAL black frame.
So far so good.

But the problem is until i reboot the rasp entirely i can never have the stream to work again.  
I have no idea what to look for or what i may have to do to setup properly the b101, information about it are very confusing.

Another things is using --dv-timing always return the following error

`Can't subscribe to V4L2_EVENT_SOURCE_CHANGE: Invalid argument`

Thanks!

Log

```
-- INFO  [1276.896      http] -- Starting HTTP eventloop ...
-- INFO  [1276.896    stream] -- Device fd=8 opened
-- INFO  [1276.896    stream] -- Using input channel: 0
-- INFO  [1276.896    stream] -- Using TV standard: DEFAULT
-- INFO  [1276.897    stream] -- Using resolution: 640x480
-- INFO  [1276.897    stream] -- Using pixelformat: UYVY
-- INFO  [1276.898    stream] -- Using HW FPS: 0 -> 90 (coerced)
-- INFO  [1276.898    stream] -- Using IO method: MMAP
-- INFO  [1276.903    stream] -- Requested 5 HW buffers, got 5
-- INFO  [1279.432    stream] -- Capturing started
-- INFO  [1279.432    stream] -- Initializing BCM ...
-- INFO  [1279.434    stream] -- Initializing OMX ...
-- INFO  [1279.435    stream] -- Initializing OMX encoder ...
-- INFO  [1279.438    stream] -- Initializing OMX encoder ...
-- INFO  [1279.440    stream] -- Initializing OMX encoder ...
-- INFO  [1279.459    stream] -- Using JPEG quality: 80%
-- INFO  [1279.459    stream] -- Creating pool with 3 workers ...
-- INFO  [1279.459    stream] -- Capturing ...
-- INFO  [1287.157      http] -- HTTP: Registered client: [192.168.1.91]:41038, id=d67c24f9-5117-43c6-933c-06f9e5e70658; clients now: 1
-- ERROR [1296.167    stream] -- Mainloop select() timeout
-- INFO  [1296.167    stream] -- Destroying workers pool ...
-- INFO  [1296.177      http] -- HTTP: Changed picture to BLANK
-- INFO  [1299.217    stream] -- Capturing stopped
-- INFO  [1299.219    stream] -- Device fd=8 closed
================================================================================
-- INFO  [1299.219    stream] -- Device fd=8 opened
-- INFO  [1299.219    stream] -- Using input channel: 0
-- INFO  [1299.219    stream] -- Using TV standard: DEFAULT
-- ERROR [1305.297    stream] -- Unable to set pixelformat=UYVY, resolution=640x480: Invalid argument
-- INFO  [1305.297    stream] -- Device fd=8 closed
-- INFO  [1305.297    stream] -- Sleeping 1 seconds before new stream init ...
================================================================================
-- INFO  [1306.297    stream] -- Device fd=8 opened
-- INFO  [1306.298    stream] -- Using input channel: 0
-- INFO  [1306.298    stream] -- Using TV standard: DEFAULT
-- INFO  [1306.298    stream] -- Using resolution: 640x480
-- INFO  [1306.298    stream] -- Using pixelformat: UYVY
-- INFO  [1306.299    stream] -- Using HW FPS: 0 -> 90 (coerced)
-- INFO  [1306.299    stream] -- Using IO method: MMAP
-- INFO  [1306.304    stream] -- Requested 5 HW buffers, got 5
-- ERROR [1312.738    stream] -- Unable to start capturing: Invalid argument
-- INFO  [1312.740    stream] -- Device fd=8 closed
-- INFO  [1312.740    stream] -- Sleeping 1 seconds before new stream init ...
================================================================================
-- INFO  [1313.740    stream] -- Device fd=8 opened
-- INFO  [1316.817    stream] -- Using input channel: 0
-- INFO  [1316.817    stream] -- Using TV standard: DEFAULT
-- ERROR [1319.655    stream] -- Unable to set pixelformat=UYVY, resolution=640x480: Invalid argument
-- INFO  [1319.655    stream] -- Device fd=8 closed
-- INFO  [1319.655    stream] -- Sleeping 1 seconds before new stream init ...
```

**Comment by mdevaev** [comment]
Which kernel and OS you're use?

**Comment by mdevaev** [comment]
Sorry, ok, raspbian. I need the kernel version.

**Comment by mdevaev** [comment]
Perhaps you might have incorrect EDID. Write me to discord and we're try to debug it using chat.

**Comment by mdevaev** [comment]
I just tested Pi-KVM and everything works fine. My users also don't report any problems. The problem is probably in your OS, so I need to run the diagnostics with you.

**Comment by depauwjimmy** [comment]
I have played around a bit after creating this issue but had to witch to something else.
I believe i have managed to make it work somehow by using dtoverlay=tc358743 and an EDID i found laying around.
What concerns me is that what would be connected to the card can be anything, i have no control over it.
Therefore it might work with the camera i tested it with but not with the computer some guy will plug next.
Is there a way for me to put an very generic EDID that make it very versatile and compatible with almost everything being plugged in?

**Comment by mdevaev** [comment]
Making EDID is a rocket science. I can't say that I have fully mastered it, perhaps you should ask the [driver developer](https://www.raspberrypi.org/forums/viewtopic.php?f=38&t=120702&start=675). You can also try my [Pi-KVM EDID](https://github.com/pikvm/kvmd/blob/master/configs/kvmd/tc358743-edid.hex), it seems to work pretty well.

Do I understand correctly that there is no problem at the moment and `--dv-timings` is working?

**Comment by mdevaev** [comment]
Okay, it seems "not-a-bug" but configuration issue. Feel free to reopen if you have any questions.
