### ISSUE TITLE
The DV-Timings URL in the README is broken (404)

### ISSUE THREAD

**Issue by rgl** [pikvm/ustreamer#41]
The URL for the DV-timings https://linuxtv.org/downloads/v4l-dvb-apis/uapi/v4l/dv-timings.html that is in the README.md is broken (404).

I'm not sure if https://linuxtv.org/downloads/v4l-dvb-apis-new/userspace-api/v4l/dv-timings.html is the new address.

**Comment by mdevaev** [comment]
Thanks, fixed
