### ISSUE TITLE
NDI Output Support

### ISSUE THREAD

**Issue by GadgetUK** [pikvm/ustreamer#58]
Would be great to include NDI output support for ultra low latency video output.

**Comment by mdevaev** [comment]
Sup. What is NDI output?

**Comment by GadgetUK** [comment]
NDI = Network Device Interface, it allows low latency video over IP. The following might give some insight, For me the use case would be as an input to OBS (Open Broadcast Studio).
https://www.youtube.com/watch?v=cX8fo74m6nc&feature=emb_title

**Comment by mdevaev** [comment]
Ustreamer currently does not have the ability to implement alternative video transfer protocols. This is a separate big job, which, moreover, I do not have the opportunity to do (at least right now).

As a temporary solution, I can suggest that you use browser source in OBS. Create a small HTML page, add the mjpeg stream using the img tag, and connect this page to OBS.

**Comment by mdevaev** [comment]
I implemented the ability to receive frames from ustreamer via shared memory. This allows you to write the stream to a file using ffmpeg or send it for processing further using pipe. I don't think NDI will be supported in the foreseeable future, but you can use ustreamer-dump or its code to make an ndi-proxy. It's better than nothing.

The small example:
```
$ ustreamer --jpeg-sink=test
$ ustreamer-dump --sink=test -o - | ffmpeg -use_wallclock_as_timestamps 1 -i pipe: -c:v libx264 test.mp4
```

**Comment by pinpox** [comment]
In case anyone stumbles across this: This software can be used instead for this purpouse https://github.com/lplassman/V4L2-to-NDI
