### ISSUE TITLE
Add ustreamer manpage to existing packages

### ISSUE THREAD

**Issue by reedy** [pikvm/ustreamer#67]
Now we have a manpage (#62), we should ship it in the OS packges :)

- [x] arch
- [x] ~~docker~~
- [x] gentoo
- [x] ~~openwrt~~

**Comment by mdevaev** [comment]
I added the manpage installation to the Makefile. The Arch package will pick this up automatically. Maybe a package for Gentoo too, but I'm not sure.

**Comment by mdevaev** [comment]
* Done for Gentoo.
* I don't think it makes sense to add it to docker because those who use docker usually look at the help on the Internet. In extreme cases `--help`.
* Openwrt packages do not contain a manpage to save disk spaceю
