### ISSUE TITLE
Streaming a V4L2 virtual device

### ISSUE THREAD

**Issue by DarkFighterLuke** [pikvm/ustreamer#71]
Is there a way to stream using a V4L2 virtual device? At the moment I can only find 5 supported formats.

Here is what I am actually doing:
`ffmpeg -i /dev/video0 -vf "format=yuv420p, crop=657:450:16:13" -f v4l2 /dev/video1`
but the format seems to be a problem for uStreamer.

**Comment by mdevaev** [comment]
Ustreamer only supports YUYV, UYVY, RGB565, RGB24 and JPEG. If the virtual device implements one of these formats, then everything will work.
