### ISSUE TITLE
CS2 HDMI :: OMX Green bug

### ISSUE THREAD

**Issue by fred2nice** [pikvm/ustreamer#73]
Hi,

I test on a Raspberry 4 8Go with CSI 2 HDMI ( https://raspberrypiwiki.com/HDMI_TO_CSI-2 )
Output HDMI from the raspberry itself to the CSI HDMI 

Good display, but lower perf
./ustreamer --device=/dev/video0 --host=0.0.0.0 --port=80 -r 1280x720 -n -l -m RGB24 --tcp-nodelay  -q 50
![2020-12-31 19_02_16-Window](https://user-images.githubusercontent.com/25772276/103421515-150c2c00-4b9d-11eb-928f-44d26911af8e.png)

If I use -c omx I obtained a bad display, but good perf.
./ustreamer --device=/dev/video0 --host=0.0.0.0 --port=80 -r 1280x720 -n -l -m RGB24 --tcp-nodelay  -q 50 -c omx
( I tried with several differents resolutions )
![2020-12-31 19_01_22-Window](https://user-images.githubusercontent.com/25772276/103421516-15a4c280-4b9d-11eb-9ee7-90cc5a943a62.png)

Settings :
v4l2-ctl --set-edid=file=../1080P50EDID.txt --fix-edid-checksums
v4l2-ctl --set-dv-bt-timings index=6

        Index: 6
        Active width: 1280
        Active height: 720
        Total width: 1980
        Total height: 750
        Frame format: progressive
        Polarities: +vsync +hsync
        Pixelclock: 74250000 Hz (50.00 frames per second)
        Horizontal frontporch: 440
        Horizontal sync: 40
        Horizontal backporch: 220
        Vertical frontporch: 5
        Vertical sync: 5
        Vertical backporch: 20
        Standards: CTA-861
        CTA-861 VIC: 19
        Flags: CE-video, has CTA-861 VIC

config.txt
start_x=1
gpu_mem=256
dtoverlay=tc358743

cmdline
cma=128M

If you have any idea ,-)
Thank You !

Kind Regards.

**Comment by mdevaev** [comment]
Try `--dv-timings` and `-m uyvy`.

**Comment by fred2nice** [comment]
Hi !

It works with --dv-timings.
Thank you !

Happy new year ,-)

**Comment by mdevaev** [comment]
Happy New Year! :)
