### ISSUE TITLE
--quality not working?

### ISSUE THREAD

**Issue by nevets963** [pikvm/ustreamer#75]
I'm using ustreamer with USB cameras and I would like to adjust/reduce the bitrate of the MJPG streams by adjusting the quality.

When I use --quality, I don't see any noticable change to the MJPG stream. The quality still looks exactly exactly the same if I use 1 or 100.

Perhaps I've misunderstood how this works? Or that this doesn't work with USB cameras?

Any help would be appreciated. Thanks!

**Comment by mdevaev** [comment]
When using hardware encoding by means of the camera itself, ustreamer accepts an already compressed jpeg stream via usb. Many cameras do not allow you to adjust the image quality.

**Comment by nevets963** [comment]
I see. Makes sense. Do you know other means to further compress the stream? I have 2 different USB cameras, both set to use 800x600. But 1 camera is roughly 3x the bitrate.

**Comment by mdevaev** [comment]
Probably the second camera does not use jpeg quantization tables. The only way to get a lower bitrate from it is to use compression on the cpu or omx.

**Comment by nevets963** [comment]
That sounds interesting. Any pointers/info to how I could do compression on CPU or OMX?

**Comment by mdevaev** [comment]
Use `--encoder=cpu` or `--encoder=omx` (only on raspberry pi).

**Comment by mdevaev** [comment]
Perhaps it's solved
