### ISSUE TITLE
Is it possible to use custom html?

### ISSUE THREAD

**Issue by Luupw3d** [pikvm/ustreamer#89]
I'm looking for a way to replace the default resources（html/css/js），just like the  original project （mjpg-streamer ） which  provide an option ( -w  ./www).

**Comment by mdevaev** [comment]
Hi. Yes, use option `--static=<dir>`. Also check `--help` if you need authorization or so.

**Comment by Luupw3d** [comment]
> Hi. Yes, use option `--static=<dir>`. Also check `--help` if you need authorization or so.

It works  well，thanks a lot.
